export const LEVELS = [
  {
    id: 1,
    nameKey: 'level1',
    objectCount: 2,
    targetCorrect: 5,
    floatSpeed: 0,
    distractors: false,
    wordsPerGame: 4,
    wordPool: [
      { word: 'Apple',  heWord: 'תפוח',    emoji: '🍎', label: 'Apple',  heLabel: 'תפוח' },
      { word: 'Dog',    heWord: 'כלב',      emoji: '🐶', label: 'Dog',    heLabel: 'כלב' },
      { word: 'Car',    heWord: 'מכונית',   emoji: '🚗', label: 'Car',    heLabel: 'מכונית' },
      { word: 'Ball',   heWord: 'כדור',     emoji: '⚽', label: 'Ball',   heLabel: 'כדור' },
      { word: 'Hat',    heWord: 'כובע',     emoji: '🎩', label: 'Hat',    heLabel: 'כובע' },
      { word: 'Cup',    heWord: 'כוס',      emoji: '☕', label: 'Cup',    heLabel: 'כוס' },
      { word: 'Pig',    heWord: 'חזיר',     emoji: '🐷', label: 'Pig',    heLabel: 'חזיר' },
      { word: 'Hen',    heWord: 'תרנגולת',  emoji: '🐔', label: 'Hen',    heLabel: 'תרנגולת' },
      { word: 'Sun',    heWord: 'שמש',      heSpeech: 'שֶׁמֶשׁ', emoji: '☀️', label: 'Sun',    heLabel: 'שמש' },
      { word: 'Moon',   heWord: 'ירח',      heSpeech: 'יָרֵחַ',  emoji: '🌙', label: 'Moon',   heLabel: 'ירח' },
      { word: 'Star',   heWord: 'כוכב',     heSpeech: 'כּוֹכָב', emoji: '⭐', label: 'Star',   heLabel: 'כוכב' },
      { word: 'Fish',   heWord: 'דג',       emoji: '🐟', label: 'Fish',   heLabel: 'דג' },
      { word: 'Bird',   heWord: 'ציפור',    heSpeech: 'צִיפּוֹר', emoji: '🐦', label: 'Bird',   heLabel: 'ציפור' },
      { word: 'Tree',   heWord: 'עץ',       emoji: '🌳', label: 'Tree',   heLabel: 'עץ' },
      { word: 'Book',   heWord: 'ספר',      emoji: '📚', label: 'Book',   heLabel: 'ספר' },
      { word: 'Bed',    heWord: 'מיטה',     emoji: '🛏️', label: 'Bed',    heLabel: 'מיטה' },
      { word: 'Milk',   heWord: 'חלב',      heSpeech: 'חָלָב',   emoji: '🥛', label: 'Milk',   heLabel: 'חלב' },
      { word: 'Egg',    heWord: 'ביצה',     heSpeech: 'בֵּיצָה', emoji: '🥚', label: 'Egg',    heLabel: 'ביצה' },
      { word: 'Cake',   heWord: 'עוגה',     emoji: '🎂', label: 'Cake',   heLabel: 'עוגה' },
      { word: 'Duck',   heWord: 'ברווז',    heSpeech: 'בַּרְוָז', emoji: '🦆', label: 'Duck',   heLabel: 'ברווז' },
      { word: 'Bear',   heWord: 'דוב',      emoji: '🐻', label: 'Bear',   heLabel: 'דוב' },
      { word: 'Bee',    heWord: 'דבורה',    heSpeech: 'דְּבוֹרָה', emoji: '🐝', label: 'Bee',    heLabel: 'דבורה' },
      { word: 'Cow',    heWord: 'פרה',      heSpeech: 'פָּרָה',  emoji: '🐮', label: 'Cow',    heLabel: 'פרה' },
      { word: 'Ice',    heWord: 'קרח',      emoji: '🧊', label: 'Ice',    heLabel: 'קרח' },
      { word: 'Ant',    heWord: 'נמלה',     heSpeech: 'נְמָלָה', emoji: '🐜', label: 'Ant',    heLabel: 'נמלה' },
      { word: 'Owl',    heWord: 'ינשוף',    heSpeech: 'יַנְשׁוּף', emoji: '🦉', label: 'Owl',    heLabel: 'ינשוף' },
      { word: 'Key',    heWord: 'מפתח',     heSpeech: 'מַפְתֵּחַ', emoji: '🔑', label: 'Key',    heLabel: 'מפתח' },
      { word: 'Corn',   heWord: 'תירס',     emoji: '🌽', label: 'Corn',   heLabel: 'תירס' },
    ],
  },
  {
    id: 2,
    nameKey: 'level2',
    objectCount: 3,
    targetCorrect: 7,
    floatSpeed: 1,
    distractors: false,
    wordsPerGame: 5,
    wordPool: [
      { word: 'Cat',   heWord: 'חתול',    emoji: '🐱', label: 'Cat',   heLabel: 'חתול' },
      { word: 'Cap',   heWord: 'כובע',    emoji: '🧢', label: 'Cap',   heLabel: 'כובע' },
      { word: 'Ship',  heWord: 'ספינה',   emoji: '🚢', label: 'Ship',  heLabel: 'ספינה' },
      { word: 'Sheep', heWord: 'כבש',     heSpeech: 'כֶּבֶשׂ',  emoji: '🐑', label: 'Sheep', heLabel: 'כבש' },
      { word: 'Bus',   heWord: 'אוטובוס', emoji: '🚌', label: 'Bus',   heLabel: 'אוטובוס' },
      { word: 'Bat',   heWord: 'עטלף',    heSpeech: 'עַטַלֵף',  emoji: '🦇', label: 'Bat',   heLabel: 'עטלף' },
      { word: 'Pan',   heWord: 'מחבת',    heSpeech: 'מַחֲבַת',  emoji: '🍳', label: 'Pan',   heLabel: 'מחבת' },
      { word: 'Pen',   heWord: 'עט',      emoji: '🖊️', label: 'Pen',   heLabel: 'עט' },
      { word: 'Fox',   heWord: 'שועל',    heSpeech: 'שׁוּעָל',  emoji: '🦊', label: 'Fox',   heLabel: 'שועל' },
      { word: 'Box',   heWord: 'קופסה',   heSpeech: 'קוּפְסָה', emoji: '📦', label: 'Box',   heLabel: 'קופסה' },
      { word: 'Jet',   heWord: 'מטוס',    emoji: '✈️', label: 'Jet',   heLabel: 'מטוס' },
      { word: 'Lamp',  heWord: 'מנורה',   emoji: '💡', label: 'Lamp',  heLabel: 'מנורה' },
      { word: 'Sock',  heWord: 'גרב',     emoji: '🧦', label: 'Sock',  heLabel: 'גרב' },
      { word: 'Bell',  heWord: 'פעמון',   emoji: '🔔', label: 'Bell',  heLabel: 'פעמון' },
      { word: 'Rock',  heWord: 'סלע',     emoji: '🪨', label: 'Rock',  heLabel: 'סלע' },
      { word: 'Net',   heWord: 'רשת',     emoji: '🥅', label: 'Net',   heLabel: 'רשת' },
      { word: 'Nut',   heWord: 'אגוז',    emoji: '🥜', label: 'Nut',   heLabel: 'אגוז' },
      { word: 'Mug',   heWord: 'ספל',     emoji: '☕', label: 'Mug',   heLabel: 'ספל' },
      { word: 'Nest',  heWord: 'קן',      emoji: '🪺', label: 'Nest',  heLabel: 'קן' },
      { word: 'Tent',  heWord: 'אוהל',    emoji: '⛺', label: 'Tent',  heLabel: 'אוהל' },
      { word: 'Lock',  heWord: 'מנעול',   emoji: '🔒', label: 'Lock',  heLabel: 'מנעול' },
      { word: 'Bun',   heWord: 'לחמנייה', emoji: '🍞', label: 'Bun',   heLabel: 'לחמנייה' },
      { word: 'Pear',  heWord: 'אגס',     emoji: '🍐', label: 'Pear',  heLabel: 'אגס' },
      { word: 'Map',   heWord: 'מפה',     emoji: '🗺️', label: 'Map',   heLabel: 'מפה' },
      { word: 'Frog',  heWord: 'צפרדע',   emoji: '🐸', label: 'Frog',  heLabel: 'צפרדע' },
    ],
  },
  {
    id: 3,
    nameKey: 'level3',
    objectCount: 3,
    targetCorrect: 7,
    floatSpeed: 1,
    distractors: true,
    wordsPerGame: 4,
    wordPool: [
      { word: 'Crab',   heWord: 'סרטן',   emoji: '🦀', label: 'Crab',   heLabel: 'סרטן' },
      { word: 'Drum',   heWord: 'תוף',    emoji: '🥁', label: 'Drum',   heLabel: 'תוף' },
      { word: 'Crown',  heWord: 'כתר',    emoji: '👑', label: 'Crown',  heLabel: 'כתר' },
      { word: 'Truck',  heWord: 'משאית',  emoji: '🚛', label: 'Truck',  heLabel: 'משאית' },
      { word: 'Shark',  heWord: 'כריש',   emoji: '🦈', label: 'Shark',  heLabel: 'כריש' },
      { word: 'Snail',  heWord: 'שבלול',  emoji: '🐌', label: 'Snail',  heLabel: 'שבלול' },
      { word: 'Grapes', heWord: 'ענבים',  emoji: '🍇', label: 'Grapes', heLabel: 'ענבים' },
      { word: 'Cloud',  heWord: 'ענן',    emoji: '☁️', label: 'Cloud',  heLabel: 'ענן' },
      { word: 'Train',  heWord: 'רכבת',   emoji: '🚂', label: 'Train',  heLabel: 'רכבת' },
      { word: 'Broom',  heWord: 'מטאטא',  emoji: '🧹', label: 'Broom',  heLabel: 'מטאטא' },
      { word: 'Glove',  heWord: 'כפפה',   emoji: '🧤', label: 'Glove',  heLabel: 'כפפה' },
      { word: 'Dress',  heWord: 'שמלה',   emoji: '👗', label: 'Dress',  heLabel: 'שמלה' },
      { word: 'Brick',  heWord: 'לבנה',   emoji: '🧱', label: 'Brick',  heLabel: 'לבנה' },
      { word: 'Plum',   heWord: 'שזיף',   emoji: '🫐', label: 'Plum',   heLabel: 'שזיף' },
      { word: 'Whale',  heWord: 'לוויתן', emoji: '🐳', label: 'Whale',  heLabel: 'לוויתן' },
      { word: 'Eagle',  heWord: 'נשר',    emoji: '🦅', label: 'Eagle',  heLabel: 'נשר' },
      { word: 'Storm',  heWord: 'סופה',   emoji: '⛈️', label: 'Storm',  heLabel: 'סופה' },
      { word: 'Flame',  heWord: 'אש',     emoji: '🔥', label: 'Flame',  heLabel: 'אש' },
      { word: 'Straw',  heWord: 'קש',     emoji: '🥤', label: 'Straw',  heLabel: 'קש' },
      { word: 'Skunk',  heWord: 'בואש',   heSpeech: 'בּוּאָשׁ', emoji: '🦨', label: 'Skunk',  heLabel: 'בואש' },
      { word: 'Stone',  heWord: 'אבן',    emoji: '🪨', label: 'Stone',  heLabel: 'אבן' },
      { word: 'Slide',  heWord: 'מגלשה',  emoji: '🛝', label: 'Slide',  heLabel: 'מגלשה' },
      { word: 'Swing',  heWord: 'נדנדה',  emoji: '🎠', label: 'Swing',  heLabel: 'נדנדה' },
    ],
  },
  {
    id: 4,
    nameKey: 'level4',
    objectCount: 3,
    targetCorrect: 10,
    floatSpeed: 2,
    distractors: false,
    wordsPerGame: 4,
    wordPool: [
      { word: 'Tiger',      heWord: 'נמר',       emoji: '🐯', label: 'Tiger',      heLabel: 'נמר' },
      { word: 'Rabbit',     heWord: 'ארנב',      emoji: '🐰', label: 'Rabbit',     heLabel: 'ארנב' },
      { word: 'Monkey',     heWord: 'קוף',       emoji: '🐒', label: 'Monkey',     heLabel: 'קוף' },
      { word: 'Penguin',    heWord: 'פינגווין',  emoji: '🐧', label: 'Penguin',    heLabel: 'פינגווין' },
      { word: 'Turtle',     heWord: 'צב',        emoji: '🐢', label: 'Turtle',     heLabel: 'צב' },
      { word: 'Dragon',     heWord: 'דרקון',     emoji: '🐉', label: 'Dragon',     heLabel: 'דרקון' },
      { word: 'Rocket',     heWord: 'רקטה',      heSpeech: 'רָקֶטָה', emoji: '🚀', label: 'Rocket',     heLabel: 'רקטה' },
      { word: 'Cactus',     heWord: 'קקטוס',     emoji: '🌵', label: 'Cactus',     heLabel: 'קקטוס' },
      { word: 'Elephant',   heWord: 'פיל',       emoji: '🐘', label: 'Elephant',   heLabel: 'פיל' },
      { word: 'Dinosaur',   heWord: 'דינוזאור',  emoji: '🦕', label: 'Dinosaur',   heLabel: 'דינוזאור' },
      { word: 'Kangaroo',   heWord: 'קנגורו',    emoji: '🦘', label: 'Kangaroo',   heLabel: 'קנגורו' },
      { word: 'Octopus',    heWord: 'תמנון',     emoji: '🐙', label: 'Octopus',    heLabel: 'תמנון' },
      { word: 'Volcano',    heWord: 'הר געש',    emoji: '🌋', label: 'Volcano',    heLabel: 'הר געש' },
      { word: 'Unicorn',    heWord: 'חד קרן',    emoji: '🦄', label: 'Unicorn',    heLabel: 'חד קרן' },
      { word: 'Umbrella',   heWord: 'מטריה',     emoji: '☂️', label: 'Umbrella',   heLabel: 'מטריה' },
      { word: 'Crocodile',  heWord: 'תנין',      emoji: '🐊', label: 'Crocodile',  heLabel: 'תנין' },
      { word: 'Flamingo',   heWord: 'פלמינגו',   emoji: '🦩', label: 'Flamingo',   heLabel: 'פלמינגו' },
      { word: 'Helicopter', heWord: 'מסוק',      emoji: '🚁', label: 'Helicopter', heLabel: 'מסוק' },
      { word: 'Strawberry', heWord: 'תות',       emoji: '🍓', label: 'Strawberry', heLabel: 'תות' },
      { word: 'Pineapple',  heWord: 'אננס',      emoji: '🍍', label: 'Pineapple',  heLabel: 'אננס' },
      { word: 'Scorpion',   heWord: 'עקרב',      heSpeech: 'עַקְרָב', emoji: '🦂', label: 'Scorpion',   heLabel: 'עקרב' },
      { word: 'Jellyfish',  heWord: 'מדוזה',     emoji: '🪼', label: 'Jellyfish',  heLabel: 'מדוזה' },
      { word: 'Peacock',    heWord: 'טווס',      emoji: '🦚', label: 'Peacock',    heLabel: 'טווס' },
    ],
  },
];

export const DISTRACTOR_POOL = [
  { emoji: '🌈', label: 'Rainbow',   heLabel: 'קשת' },
  { emoji: '🎈', label: 'Balloon',   heLabel: 'בלון' },
  { emoji: '🦋', label: 'Butterfly', heLabel: 'פרפר' },
  { emoji: '🌺', label: 'Hibiscus',  heLabel: 'פרח' },
];
