export const LEVELS = [
  {
    id: 1,
    nameKey: 'level1',
    objectCount: 2,
    targetCorrect: 5,
    floatSpeed: 0,
    distractors: false,
    wordsPerGame: 4,
    wordPool: [
      { word: 'Apple',  heWord: 'תפוח',      emoji: '🍎', label: 'Apple',  heLabel: 'תפוח' },
      { word: 'Dog',    heWord: 'כלב',        emoji: '🐶', label: 'Dog',    heLabel: 'כלב' },
      { word: 'Car',    heWord: 'מכונית',     emoji: '🚗', label: 'Car',    heLabel: 'מכונית' },
      { word: 'Ball',   heWord: 'כדור',       emoji: '⚽', label: 'Ball',   heLabel: 'כדור' },
      { word: 'Hat',    heWord: 'כובע',       emoji: '🎩', label: 'Hat',    heLabel: 'כובע' },
      { word: 'Cup',    heWord: 'כוס',        emoji: '☕', label: 'Cup',    heLabel: 'כוס' },
      { word: 'Pig',    heWord: 'חזיר',       emoji: '🐷', label: 'Pig',    heLabel: 'חזיר' },
      { word: 'Hen',    heWord: 'תרנגולת',    emoji: '🐔', label: 'Hen',    heLabel: 'תרנגולת' },
    ],
  },
  {
    id: 2,
    nameKey: 'level2',
    objectCount: 3,
    targetCorrect: 7,
    floatSpeed: 1,
    distractors: false,
    wordsPerGame: 5,
    wordPool: [
      { word: 'Cat',   heWord: 'חתול',    emoji: '🐱', label: 'Cat',   heLabel: 'חתול' },
      { word: 'Cap',   heWord: 'כובע',    emoji: '🧢', label: 'Cap',   heLabel: 'כובע' },
      { word: 'Ship',  heWord: 'ספינה',   emoji: '🚢', label: 'Ship',  heLabel: 'ספינה' },
      { word: 'Sheep', heWord: 'כבש',     heSpeech: 'כֶּבֶשׂ', emoji: '🐑', label: 'Sheep', heLabel: 'כבש' },
      { word: 'Bus',   heWord: 'אוטובוס', emoji: '🚌', label: 'Bus',   heLabel: 'אוטובוס' },
      { word: 'Bat',   heWord: 'עטלף',    heSpeech: 'עַטַלֵף', emoji: '🦇', label: 'Bat',   heLabel: 'עטלף' },
      { word: 'Pan',   heWord: 'מחבת',    heSpeech: 'מַחֲבַת', emoji: '🍳', label: 'Pan',   heLabel: 'מחבת' },
      { word: 'Pen',   heWord: 'עט',      emoji: '🖊️', label: 'Pen',   heLabel: 'עט' },
      { word: 'Fox',   heWord: 'שועל',    heSpeech: 'שׁוּעָל', emoji: '🦊', label: 'Fox',   heLabel: 'שועל' },
      { word: 'Box',   heWord: 'קופסה',   heSpeech: 'קוּפְסָה', emoji: '📦', label: 'Box',   heLabel: 'קופסה' },
    ],
  },
  {
    id: 3,
    nameKey: 'level3',
    objectCount: 3,
    targetCorrect: 7,
    floatSpeed: 1,
    distractors: true,
    wordsPerGame: 4,
    wordPool: [
      { word: 'Frog',   heWord: 'צפרדע', emoji: '🐸', label: 'Frog',   heLabel: 'צפרדע' },
      { word: 'Crab',   heWord: 'סרטן',  emoji: '🦀', label: 'Crab',   heLabel: 'סרטן' },
      { word: 'Drum',   heWord: 'תוף',   emoji: '🥁', label: 'Drum',   heLabel: 'תוף' },
      { word: 'Crown',  heWord: 'כתר',   emoji: '👑', label: 'Crown',  heLabel: 'כתר' },
      { word: 'Truck',  heWord: 'משאית', emoji: '🚛', label: 'Truck',  heLabel: 'משאית' },
      { word: 'Shark',  heWord: 'כריש',  emoji: '🦈', label: 'Shark',  heLabel: 'כריש' },
      { word: 'Snail',  heWord: 'שבלול', emoji: '🐌', label: 'Snail',  heLabel: 'שבלול' },
      { word: 'Grapes', heWord: 'ענבים', emoji: '🍇', label: 'Grapes', heLabel: 'ענבים' },
    ],
  },
  {
    id: 4,
    nameKey: 'level4',
    objectCount: 3,
    targetCorrect: 10,
    floatSpeed: 2,
    distractors: false,
    wordsPerGame: 4,
    wordPool: [
      { word: 'Tiger',   heWord: 'נמר',     emoji: '🐯', label: 'Tiger',   heLabel: 'נמר' },
      { word: 'Rabbit',  heWord: 'ארנב',    emoji: '🐰', label: 'Rabbit',  heLabel: 'ארנב' },
      { word: 'Monkey',  heWord: 'קוף',     emoji: '🐒', label: 'Monkey',  heLabel: 'קוף' },
      { word: 'Penguin', heWord: 'פינגווין',emoji: '🐧', label: 'Penguin', heLabel: 'פינגווין' },
      { word: 'Turtle',  heWord: 'צב',      emoji: '🐢', label: 'Turtle',  heLabel: 'צב' },
      { word: 'Dragon',  heWord: 'דרקון',   emoji: '🐉', label: 'Dragon',  heLabel: 'דרקון' },
      { word: 'Rocket',  heWord: 'רקטה',    emoji: '🚀', label: 'Rocket',  heLabel: 'רקטה' },
      { word: 'Cactus',  heWord: 'קקטוס',   emoji: '🌵', label: 'Cactus',  heLabel: 'קקטוס' },
    ],
  },
];

export const DISTRACTOR_POOL = [
  { emoji: '🌈', label: 'Rainbow',   heLabel: 'קשת' },
  { emoji: '🎈', label: 'Balloon',   heLabel: 'בלון' },
  { emoji: '🦋', label: 'Butterfly', heLabel: 'פרפר' },
  { emoji: '🌺', label: 'Hibiscus',  heLabel: 'פרח' },
];
