// Social situations for ages 3.5–8.
// Hebrew primary. Each scenario has a video path (in public/videos/).
// If the video file is missing, the emoji scene strip is shown instead.
// Scenarios ordered: prosocial first (1-6), boundary/safety last (7-10).
//
// sceneEmojis: the 3 emojis that tell the story visually
// sceneAnims:  CSS animation class per emoji (float|shake|bounce|pulse|wave|spin|sparkle|cry|nod|none)

export const SCENARIOS = [
  {
    id: 1,
    video: 'videos/scenario-1.mp4',
    scene: '🧒😤🪀',
    sceneEmojis: ['🧒', '😤', '🪀'],
    sceneAnims:  ['float', 'shake', 'bounce'],
    // child stands → frustration vibrates → toy bounces away
    situation: 'חבר לקח את הצעצוע שלך',
    situationEn: 'A friend took your toy',
    tts: 'חבר לקח את הצעצוע שלך. מה אתה עושה?',
    ttsFallback: 'A friend took your toy. What do you do?',
    options: [
      { emoji: '🗣️', text: 'אני אומר: "זה שלי, תחזיר בבקשה"', quality: 'best' },
      { emoji: '👊', text: 'אני דוחף אותו', quality: 'notGood' },
    ],
    lesson: 'אפשר לבקש בצורה נעימה — מילים עובדות!',
    lessonFallback: 'Ask nicely — words work!',
    responseLevel: 1,
  },
  {
    id: 2,
    video: 'videos/scenario-2.mp4',
    scene: '🧒😢👫',
    sceneEmojis: ['🧒', '😢', '👫'],
    sceneAnims:  ['float', 'cry', 'bounce'],
    // lonely child floats → tear drops → friends bounce together
    situation: 'אף אחד לא רוצה לשחק איתי',
    situationEn: 'Nobody wants to play with me',
    tts: 'אף אחד לא רוצה לשחק איתך. מה אתה עושה?',
    ttsFallback: 'Nobody wants to play with you. What do you do?',
    options: [
      { emoji: '🤗', text: 'אני ניגש ואומר: "אפשר לשחק?"', quality: 'best' },
      { emoji: '😭', text: 'אני בוכה ובורח', quality: 'notGood' },
    ],
    lesson: 'לשאול בנחמדות — זו הדרך הטובה ביותר להצטרף!',
    lessonFallback: 'Asking nicely is the best way to join!',
    responseLevel: 1,
  },
  {
    id: 3,
    video: 'videos/scenario-3.mp4',
    scene: '⚽👫🙋',
    sceneEmojis: ['⚽', '👫', '🙋'],
    sceneAnims:  ['spin', 'bounce', 'wave'],
    // ball spins → friends bounce playing → hand raises to ask
    situation: 'אני רוצה להצטרף למשחק של חברים',
    situationEn: 'I want to join my friends\' game',
    tts: 'אתה רוצה להצטרף למשחק. מה אתה עושה?',
    ttsFallback: 'You want to join the game. What do you do?',
    options: [
      { emoji: '😊', text: 'אני ניגש ואומר: "אפשר גם אני?"', quality: 'best' },
      { emoji: '😠', text: 'אני לוקח את הכדור בלי לשאול', quality: 'notGood' },
    ],
    lesson: 'לשאול בנחמדות — זה הסוד להצטרפות!',
    lessonFallback: 'Asking kindly is the secret to joining!',
    responseLevel: 1,
  },
  {
    id: 4,
    video: 'videos/scenario-4.mp4',
    scene: '🧒😢💙',
    sceneEmojis: ['🧒', '😢', '💙'],
    sceneAnims:  ['float', 'cry', 'pulse'],
    // child stands → sad face droops → heart pulses with care
    situation: 'חבר שלי בוכה ועצוב',
    situationEn: 'My friend is crying and sad',
    tts: 'חבר שלך בוכה ועצוב. מה אתה עושה?',
    ttsFallback: 'Your friend is crying and sad. What do you do?',
    options: [
      { emoji: '🤗', text: 'אני ניגש ואומר: "אני כאן בשבילך"', quality: 'best' },
      { emoji: '🏃', text: 'אני ממשיך לשחק לבד', quality: 'notGood' },
    ],
    lesson: 'להיות שם לחבר — זה אחד הדברים הכי יפים!',
    lessonFallback: 'Being there for a friend is one of the nicest things!',
    responseLevel: 1,
  },
  {
    id: 5,
    video: 'videos/scenario-5.mp4',
    scene: '🧒😳💔',
    sceneEmojis: ['🧒', '😳', '💔'],
    sceneAnims:  ['shake', 'pulse', 'pulse'],
    // child trembles with guilt → shocked face pulses → broken heart pulses
    situation: 'עשיתי טעות ושברתי משהו',
    situationEn: 'I made a mistake and broke something',
    tts: 'עשית טעות ושברת משהו. מה אתה עושה?',
    ttsFallback: 'You made a mistake and broke something. What do you do?',
    options: [
      { emoji: '🙏', text: 'אני אומר: "סליחה, עשיתי בטעות"', quality: 'best' },
      { emoji: '🏃', text: 'אני בורח ולא אומר כלום', quality: 'notGood' },
    ],
    lesson: 'לומר "סליחה" הוא אחד הדברים האמיצים ביותר!',
    lessonFallback: 'Saying "sorry" is one of the bravest things!',
    responseLevel: 1,
  },
  {
    id: 6,
    video: 'videos/scenario-6.mp4',
    scene: '🧒💢🧒',
    sceneEmojis: ['🧒', '💢', '🧒'],
    sceneAnims:  ['shake', 'pulse', 'float'],
    // pushed child shakes → anger symbol pulses → pusher stands
    situation: 'חבר דוחף אותי',
    situationEn: 'A friend is pushing me',
    tts: 'חבר דוחף אותך. מה אתה עושה?',
    ttsFallback: 'A friend is pushing you. What do you do?',
    options: [
      { emoji: '🙋', text: 'אני אומר "אל תדחוף" ומספר למורה', quality: 'best' },
      { emoji: '👊', text: 'אני דוחף בחזרה', quality: 'notGood' },
    ],
    lesson: 'דחיפה כואבת — מורה תעזור לך!',
    lessonFallback: 'Pushing hurts — a teacher will help you!',
    responseLevel: 3,
  },
  {
    id: 7,
    video: 'videos/scenario-7.mp4',
    scene: '🧒😠🤝',
    sceneEmojis: ['🧒', '😠', '🤝'],
    sceneAnims:  ['float', 'shake', 'pulse'],
    // child stands firm → angry face shakes (threat) → handshake pulses (the right choice)
    situation: 'מישהו אומר: "אם לא תיתן לי, אני לא חבר שלך"',
    situationEn: '"If you don\'t give me that, I\'m not your friend"',
    tts: 'מישהו אומר — אם לא תיתן לי, אני לא חבר שלך. מה אתה עושה?',
    ttsFallback: 'Someone says — if you don\'t give me that, I\'m not your friend. What do you do?',
    options: [
      { emoji: '💪', text: 'אני אומר: "חבר אמיתי לא מאיים"', quality: 'best' },
      { emoji: '😰', text: 'אני נותן לו כי אני פוחד', quality: 'notGood' },
    ],
    lesson: 'חבר טוב לא מאיים — מותר לומר לא!',
    lessonFallback: 'A good friend does not threaten — it\'s OK to say no!',
    responseLevel: 1,
  },
  {
    id: 8,
    video: 'videos/scenario-8.mp4',
    scene: '🧒😤😆',
    sceneEmojis: ['🧒', '😤', '😆'],
    sceneAnims:  ['float', 'shake', 'bounce'],
    // victim floats sadly → frustration shakes → mocking laughter bounces
    situation: 'מישהו צוחק עליי',
    situationEn: 'Someone is laughing at me',
    tts: 'מישהו צוחק עליך. מה אתה עושה?',
    ttsFallback: 'Someone is laughing at you. What do you do?',
    options: [
      { emoji: '🚶', text: 'אני מתרחק ומספר למורה', quality: 'best' },
      { emoji: '😡', text: 'אני צועק עליו בחזרה', quality: 'notGood' },
    ],
    lesson: 'להתרחק ולספר למבוגר — זה הכוח האמיתי!',
    lessonFallback: 'Walking away and telling an adult — that\'s real strength!',
    responseLevel: 3,
  },
  {
    id: 9,
    video: 'videos/scenario-9.mp4',
    scene: '🤫😨🙅',
    sceneEmojis: ['🤫', '😨', '🙅'],
    sceneAnims:  ['pulse', 'shake', 'wave'],
    // shushing pulses with pressure → fear shakes → no-sign waves (boundary)
    // Note: may need adult facilitation for younger/autistic children
    situation: 'מישהו מבקש שאשמור סוד שמפחיד אותי',
    situationEn: 'Someone asks me to keep a secret that scares me',
    tts: 'מישהו מבקש ממך לשמור סוד שמפחיד אותך. מה אתה עושה?',
    ttsFallback: 'Someone asks you to keep a secret that scares you. What do you do?',
    options: [
      { emoji: '👩‍🏫', text: 'אני מספר לאמא, אבא, או מורה', quality: 'best' },
      { emoji: '🤐', text: 'אני שומר את הסוד לבד', quality: 'notGood' },
    ],
    lesson: 'סוד שמפחיד — חייבים לספר למבוגר שסומכים עליו!',
    lessonFallback: 'A scary secret — always tell a trusted adult!',
    responseLevel: 3,
  },
  {
    id: 10,
    video: 'videos/scenario-10.mp4',
    scene: '🧒😟🚫',
    sceneEmojis: ['🧒', '😟', '🚫'],
    sceneAnims:  ['float', 'cry', 'pulse'],
    // child floats uncertain → worried face droops → stop-sign pulses
    situation: 'חבר אומר לי לעשות משהו שנראה לא בסדר',
    situationEn: 'A friend wants me to do something that feels wrong',
    tts: 'חבר מבקש ממך לעשות משהו שנראה לא בסדר. מה אתה עושה?',
    ttsFallback: 'A friend asks you to do something that feels wrong. What do you do?',
    options: [
      { emoji: '🙅', text: 'אני אומר "לא" ומספר למבוגר', quality: 'best' },
      { emoji: '😰', text: 'אני עושה כי הוא חבר שלי', quality: 'notGood' },
    ],
    lesson: 'אפשר תמיד לומר לא לדבר שמרגיש לא בסדר!',
    lessonFallback: 'You can always say no to something that feels wrong!',
    responseLevel: 3,
  },
  {
    id: 11,
    video: 'videos/scenario-11.mp4',
    scene: '🎢🧒⏳',
    sceneEmojis: ['🎢', '🧒', '⏳'],
    sceneAnims:  ['bounce', 'float', 'pulse'],
    // slide bounces (inviting) → child waits patiently → hourglass pulses (time passing)
    situation: 'אני מחכה בתור לגלשן וזה לוקח הרבה זמן',
    situationEn: 'I am waiting in line for the slide and it takes a long time',
    tts: 'אתה מחכה בתור לגלשן וזה לוקח הרבה זמן. מה אתה עושה?',
    ttsFallback: 'You are waiting in line for the slide and it takes a long time. What do you do?',
    options: [
      { emoji: '😌', text: 'אני מחכה בסבלנות — יגיע התור שלי', quality: 'best' },
      { emoji: '😤', text: 'אני דוחף לפנים כי אני לא רוצה לחכות', quality: 'notGood' },
    ],
    lesson: 'לחכות בסבלנות — כולם מקבלים את התור שלהם!',
    lessonFallback: 'Waiting patiently — everyone gets their turn!',
    responseLevel: 1,
  },
  {
    id: 12,
    video: 'videos/scenario-12.mp4',
    scene: '🎲😢🏆',
    sceneEmojis: ['🎲', '😢', '🏆'],
    sceneAnims:  ['spin', 'cry', 'sparkle'],
    // dice spins (game chance) → sad face droops (loss) → trophy sparkles (goal)
    situation: 'הפסדתי במשחק',
    situationEn: 'I lost the game',
    tts: 'הפסדת במשחק. מה אתה עושה?',
    ttsFallback: 'You lost the game. What do you do?',
    options: [
      { emoji: '🤝', text: 'אני אומר: "שיחקת טוב — נשחק שוב?"', quality: 'best' },
      { emoji: '😡', text: 'אני זורק את הקלפים ועוזב', quality: 'notGood' },
    ],
    lesson: 'לפעמים מפסידים — חשוב לשחק שוב ביחד!',
    lessonFallback: 'Sometimes we lose — what matters is playing again together!',
    responseLevel: 1,
  },
  {
    id: 13,
    video: 'videos/scenario-13.mp4',
    scene: '🧒👋😊',
    sceneEmojis: ['🧒', '👋', '😊'],
    sceneAnims:  ['float', 'wave', 'sparkle'],
    // child approaches → hand waves hello → warm smile sparkles
    situation: 'יש ילד חדש בגן ואני רוצה להכיר אותו',
    situationEn: 'There is a new kid at school and I want to meet them',
    tts: 'יש ילד חדש בגן ואתה רוצה להכיר אותו. מה אתה עושה?',
    ttsFallback: 'There is a new kid at school and you want to meet them. What do you do?',
    options: [
      { emoji: '😊', text: 'אני ניגש ואומר: "שלום, אני [שם]. מה שמך?"', quality: 'best' },
      { emoji: '🙈', text: 'אני מסתתר ולא אומר כלום', quality: 'notGood' },
    ],
    lesson: 'להגיד שלום — זה איך שמתחילה חברות חדשה!',
    lessonFallback: 'Saying hello — that\'s how a new friendship begins!',
    responseLevel: 1,
  },
  {
    id: 14,
    video: 'videos/scenario-14.mp4',
    scene: '🧒💥🧒',
    sceneEmojis: ['🧒', '💥', '🧒'],
    sceneAnims:  ['shake', 'pulse', 'float'],
    // fallen child shakes from impact → crash burst pulses → the other child floats (by accident)
    situation: 'ילד נתקל בי בטעות ואני נפלתי',
    situationEn: 'A child bumped into me by accident and I fell',
    tts: 'ילד נתקל בך בטעות ואתה נפלת. מה אתה עושה?',
    ttsFallback: 'A child bumped into you by accident and you fell. What do you do?',
    options: [
      { emoji: '😌', text: 'אני שואל: "האם היה בטעות?" — ואומר בסדר', quality: 'best' },
      { emoji: '😡', text: 'אני מיד צועק עליו', quality: 'notGood' },
    ],
    lesson: 'לפני כעס — לבדוק אם זה היה בטעות!',
    lessonFallback: 'Before getting angry — check if it was an accident!',
    responseLevel: 2,
  },
  {
    id: 15,
    video: 'videos/scenario-15.mp4',
    scene: '🚗🧒🤲',
    sceneEmojis: ['🚗', '🧒', '🤲'],
    sceneAnims:  ['bounce', 'float', 'wave'],
    // toy car bounces (moving/desirable) → child floats → open hands wave/reach
    situation: 'חבר מבקש לשאול את המכונית שלי',
    situationEn: 'A friend asks to borrow my toy car',
    tts: 'חבר מבקש לשאול את המכונית שלך. מה אתה עושה?',
    ttsFallback: 'A friend asks to borrow your toy car. What do you do?',
    options: [
      { emoji: '😊', text: 'אני נותן לו לזמן קצר ומחכה שיחזיר', quality: 'best' },
      { emoji: '🙅', text: 'אני אומר "לא!" ולא מסביר למה', quality: 'notGood' },
    ],
    lesson: 'לחלוק לזמן קצר — זה מה שחברים עושים!',
    lessonFallback: 'Sharing for a bit — that\'s what friends do!',
    responseLevel: 1,
  },
  {
    id: 16,
    video: 'videos/scenario-16.mp4',
    scene: '🎂👫😢',
    sceneEmojis: ['🎂', '👫', '😢'],
    sceneAnims:  ['pulse', 'bounce', 'cry'],
    // cake pulses (party happening) → friends bounce together → excluded child cries
    situation: 'כולם משחקים ביחד ואני לא מוזמן',
    situationEn: 'Everyone is playing together and I am not invited',
    tts: 'כולם משחקים ביחד ואתה לא מוזמן. מה אתה עושה?',
    ttsFallback: 'Everyone is playing together and you are not invited. What do you do?',
    options: [
      { emoji: '🤗', text: 'אני ניגש ואומר: "אפשר לשחק גם אני?"', quality: 'best' },
      { emoji: '😭', text: 'אני עומד בצד ובוכה לבד', quality: 'notGood' },
    ],
    lesson: 'לשאול בנחמדות — לפעמים צריך רק לבקש!',
    lessonFallback: 'Asking nicely — sometimes you just need to ask!',
    responseLevel: 1,
  },
  {
    id: 17,
    video: 'videos/scenario-17.mp4',
    scene: '🧒😵‍💫🔊',
    sceneEmojis: ['🧒', '😵‍💫', '🔊'],
    sceneAnims:  ['shake', 'shake', 'pulse'],
    // overwhelmed child shakes → dizzy/sensory face shakes → loud sound pulses
    situation: 'יש הרבה רעש ואני מרגיש המום',
    situationEn: 'There is a lot of noise and I feel overwhelmed',
    tts: 'יש הרבה רעש ואתה מרגיש המום. מה אתה עושה?',
    ttsFallback: 'There is a lot of noise and you feel overwhelmed. What do you do?',
    options: [
      { emoji: '🧘', text: 'אני הולך לפינה שקטה או מבקש עזרה מהמורה', quality: 'best' },
      { emoji: '🤯', text: 'אני צועק על כולם שיהיו שקטים', quality: 'notGood' },
    ],
    lesson: 'כשקשה — מותר לבקש מקום שקט!',
    lessonFallback: 'When it\'s too much — it\'s OK to ask for a quiet spot!',
    responseLevel: 2,
  },
  {
    id: 18,
    video: 'videos/scenario-18.mp4',
    scene: '🧒🤕👀',
    sceneEmojis: ['🧒', '🤕', '👀'],
    sceneAnims:  ['bounce', 'pulse', 'nod'],
    // hurt child bounces (just fell) → hurt face pulses with pain → eyes nod looking
    situation: 'ילד נפל ונפצע ואני ראיתי',
    situationEn: 'A child fell and got hurt and I saw it',
    tts: 'ילד נפל ונפצע ואתה ראית. מה אתה עושה?',
    ttsFallback: 'A child fell and got hurt and you saw it. What do you do?',
    options: [
      { emoji: '🏃', text: 'אני קורא למורה מיד', quality: 'best' },
      { emoji: '😶', text: 'אני ממשיך לשחק כאילו לא ראיתי', quality: 'notGood' },
    ],
    lesson: 'כשמישהו נפצע — לקרוא למבוגר מיד זה הדבר הנכון!',
    lessonFallback: 'When someone is hurt — calling an adult right away is the right thing!',
    responseLevel: 2,
  },
  {
    id: 19,
    video: 'videos/scenario-19.mp4',
    scene: '🎨🧒⭐',
    sceneEmojis: ['🎨', '🧒', '⭐'],
    sceneAnims:  ['float', 'float', 'sparkle'],
    // painting floats (artwork displayed) → child floats proudly → star sparkles with praise
    situation: 'הציור של החבר שלי יצא יפה מאוד',
    situationEn: 'My friend\'s drawing came out really beautiful',
    tts: 'הציור של חברך יצא יפה מאוד. מה אתה עושה?',
    ttsFallback: 'Your friend\'s drawing came out really beautiful. What do you do?',
    options: [
      { emoji: '😊', text: 'אני אומר: "וואו, הציור שלך יפה מאוד!"', quality: 'best' },
      { emoji: '😤', text: 'אני אומר: "שלי יותר יפה ממך"', quality: 'notGood' },
    ],
    lesson: 'לשבח חבר — זה גורם לשניכם להרגיש טוב!',
    lessonFallback: 'Complimenting a friend — it makes you both feel good!',
    responseLevel: 1,
  },
  {
    id: 20,
    video: 'videos/scenario-20.mp4',
    scene: '🧒😍🚂',
    sceneEmojis: ['🧒', '😍', '🚂'],
    sceneAnims:  ['float', 'pulse', 'bounce'],
    // child floats wanting → desire-eyes pulse → train bounces (the coveted toy)
    situation: 'אני ורעי רוצים את אותו הצעצוע בדיוק',
    situationEn: 'Me and my friend both want the exact same toy',
    tts: 'אתה ורעך רוצים את אותו הצעצוע. מה אתה עושה?',
    ttsFallback: 'You and your friend both want the same toy. What do you do?',
    options: [
      { emoji: '⏱️', text: 'אני משתמש קצת, אחר כך הוא משתמש', quality: 'best' },
      { emoji: '👊', text: 'אני לוקח את הצעצוע בכוח', quality: 'notGood' },
    ],
    lesson: 'תורות — שניכם תשחקו ושניכם תהיו שמחים!',
    lessonFallback: 'Taking turns — you both get to play and you both stay happy!',
    responseLevel: 1,
  },
];
