// Social situations for ages 3.5–8.
// Hebrew primary. Each scenario has a video path (in public/videos/).
// If the video file is missing, the emoji scene strip is shown instead.
// Scenarios ordered: prosocial first (1-6), boundary/safety last (7-10).

export const SCENARIOS = [
  {
    id: 1,
    video: 'videos/scenario-1.mp4',
    scene: '🧒😤🪀',
    situation: 'חבר לקח את הצעצוע שלך',
    situationEn: 'A friend took your toy',
    tts: 'חבר לקח את הצעצוע שלך. מה אתה עושה?',
    ttsFallback: 'A friend took your toy. What do you do?',
    options: [
      { emoji: '🗣️', text: 'אני אומר: "זה שלי, תחזיר בבקשה"', quality: 'best' },
      { emoji: '👊', text: 'אני דוחף אותו', quality: 'notGood' },
    ],
    lesson: 'אפשר לבקש בצורה נעימה — מילים עובדות!',
    lessonFallback: 'Ask nicely — words work!',
    responseLevel: 1,
  },
  {
    id: 2,
    video: 'videos/scenario-2.mp4',
    scene: '🧒😢👫',
    situation: 'אף אחד לא רוצה לשחק איתי',
    situationEn: 'Nobody wants to play with me',
    tts: 'אף אחד לא רוצה לשחק איתך. מה אתה עושה?',
    ttsFallback: 'Nobody wants to play with you. What do you do?',
    options: [
      { emoji: '🤗', text: 'אני ניגש ואומר: "אפשר לשחק?"', quality: 'best' },
      { emoji: '😭', text: 'אני בוכה ובורח', quality: 'notGood' },
    ],
    lesson: 'לשאול בנחמדות — זו הדרך הטובה ביותר להצטרף!',
    lessonFallback: 'Asking nicely is the best way to join!',
    responseLevel: 1,
  },
  {
    id: 3,
    video: 'videos/scenario-3.mp4',
    scene: '⚽👫🙋',
    situation: 'אני רוצה להצטרף למשחק של חברים',
    situationEn: 'I want to join my friends\' game',
    tts: 'אתה רוצה להצטרף למשחק. מה אתה עושה?',
    ttsFallback: 'You want to join the game. What do you do?',
    options: [
      { emoji: '😊', text: 'אני ניגש ואומר: "אפשר גם אני?"', quality: 'best' },
      { emoji: '😠', text: 'אני לוקח את הכדור בלי לשאול', quality: 'notGood' },
    ],
    lesson: 'לשאול בנחמדות — זה הסוד להצטרפות!',
    lessonFallback: 'Asking kindly is the secret to joining!',
    responseLevel: 1,
  },
  {
    id: 4,
    video: 'videos/scenario-4.mp4',
    scene: '🧒😢💙',
    situation: 'חבר שלי בוכה ועצוב',
    situationEn: 'My friend is crying and sad',
    tts: 'חבר שלך בוכה ועצוב. מה אתה עושה?',
    ttsFallback: 'Your friend is crying and sad. What do you do?',
    options: [
      { emoji: '🤗', text: 'אני ניגש ואומר: "אני כאן בשבילך"', quality: 'best' },
      { emoji: '🏃', text: 'אני ממשיך לשחק לבד', quality: 'notGood' },
    ],
    lesson: 'להיות שם לחבר — זה אחד הדברים הכי יפים!',
    lessonFallback: 'Being there for a friend is one of the nicest things!',
    responseLevel: 1,
  },
  {
    id: 5,
    video: 'videos/scenario-5.mp4',
    scene: '🧒😳💔',
    situation: 'עשיתי טעות ושברתי משהו',
    situationEn: 'I made a mistake and broke something',
    tts: 'עשית טעות ושברת משהו. מה אתה עושה?',
    ttsFallback: 'You made a mistake and broke something. What do you do?',
    options: [
      { emoji: '🙏', text: 'אני אומר: "סליחה, עשיתי בטעות"', quality: 'best' },
      { emoji: '🏃', text: 'אני בורח ולא אומר כלום', quality: 'notGood' },
    ],
    lesson: 'לומר "סליחה" הוא אחד הדברים האמיצים ביותר!',
    lessonFallback: 'Saying "sorry" is one of the bravest things!',
    responseLevel: 1,
  },
  {
    id: 6,
    video: 'videos/scenario-6.mp4',
    scene: '🧒💢🧒',
    situation: 'חבר דוחף אותי',
    situationEn: 'A friend is pushing me',
    tts: 'חבר דוחף אותך. מה אתה עושה?',
    ttsFallback: 'A friend is pushing you. What do you do?',
    options: [
      { emoji: '🙋', text: 'אני אומר "אל תדחוף" ומספר למורה', quality: 'best' },
      { emoji: '👊', text: 'אני דוחף בחזרה', quality: 'notGood' },
    ],
    lesson: 'דחיפה כואבת — מורה תעזור לך!',
    lessonFallback: 'Pushing hurts — a teacher will help you!',
    responseLevel: 3,
  },
  {
    id: 7,
    video: 'videos/scenario-7.mp4',
    scene: '🧒😠🤝',
    situation: 'מישהו אומר: "אם לא תיתן לי, אני לא חבר שלך"',
    situationEn: '"If you don\'t give me that, I\'m not your friend"',
    tts: 'מישהו אומר — אם לא תיתן לי, אני לא חבר שלך. מה אתה עושה?',
    ttsFallback: 'Someone says — if you don\'t give me that, I\'m not your friend. What do you do?',
    options: [
      { emoji: '💪', text: 'אני אומר: "חבר אמיתי לא מאיים"', quality: 'best' },
      { emoji: '😰', text: 'אני נותן לו כי אני פוחד', quality: 'notGood' },
    ],
    lesson: 'חבר טוב לא מאיים — מותר לומר לא!',
    lessonFallback: 'A good friend does not threaten — it\'s OK to say no!',
    responseLevel: 1,
  },
  {
    id: 8,
    video: 'videos/scenario-8.mp4',
    scene: '🧒😤😆',
    situation: 'מישהו צוחק עליי',
    situationEn: 'Someone is laughing at me',
    tts: 'מישהו צוחק עליך. מה אתה עושה?',
    ttsFallback: 'Someone is laughing at you. What do you do?',
    options: [
      { emoji: '🚶', text: 'אני מתרחק ומספר למורה', quality: 'best' },
      { emoji: '😡', text: 'אני צועק עליו בחזרה', quality: 'notGood' },
    ],
    lesson: 'להתרחק ולספר למבוגר — זה הכוח האמיתי!',
    lessonFallback: 'Walking away and telling an adult — that\'s real strength!',
    responseLevel: 3,
  },
  {
    id: 9,
    video: 'videos/scenario-9.mp4',
    scene: '🤫😨🙅',
    // Note: may need adult facilitation for younger/autistic children
    situation: 'מישהו מבקש שאשמור סוד שמפחיד אותי',
    situationEn: 'Someone asks me to keep a secret that scares me',
    tts: 'מישהו מבקש ממך לשמור סוד שמפחיד אותך. מה אתה עושה?',
    ttsFallback: 'Someone asks you to keep a secret that scares you. What do you do?',
    options: [
      { emoji: '👩‍🏫', text: 'אני מספר לאמא, אבא, או מורה', quality: 'best' },
      { emoji: '🤐', text: 'אני שומר את הסוד לבד', quality: 'notGood' },
    ],
    lesson: 'סוד שמפחיד — חייבים לספר למבוגר שסומכים עליו!',
    lessonFallback: 'A scary secret — always tell a trusted adult!',
    responseLevel: 3,
  },
  {
    id: 10,
    video: 'videos/scenario-10.mp4',
    scene: '🧒😟🚫',
    situation: 'חבר אומר לי לעשות משהו שנראה לא בסדר',
    situationEn: 'A friend wants me to do something that feels wrong',
    tts: 'חבר מבקש ממך לעשות משהו שנראה לא בסדר. מה אתה עושה?',
    ttsFallback: 'A friend asks you to do something that feels wrong. What do you do?',
    options: [
      { emoji: '🙅', text: 'אני אומר "לא" ומספר למבוגר', quality: 'best' },
      { emoji: '😰', text: 'אני עושה כי הוא חבר שלי', quality: 'notGood' },
    ],
    lesson: 'אפשר תמיד לומר לא לדבר שמרגיש לא בסדר!',
    lessonFallback: 'You can always say no to something that feels wrong!',
    responseLevel: 3,
  },
];
