// Level 1: 2 cards (1 target + 1 foil), simple common words
// Level 2: 3 cards (1 target + 2 foils), broader vocabulary
// Level 3: 4 cards (1 target + 3 foils), full card set, new words
// Level 4: 4 cards, all words combined — widest pool, hardest discrimination

export const LEVELS = [
  {
    id: 1,
    cardCount: 2,
    winsToWin: 5,
    wordPool: [
      { word: 'Apple',  heWord: 'תפוח',    emoji: '🍎', cat: 'food'     },
      { word: 'Dog',    heWord: 'כלב',     emoji: '🐶', cat: 'animals'  },
      { word: 'Car',    heWord: 'מכונית',  emoji: '🚗', cat: 'vehicles' },
      { word: 'Ball',   heWord: 'כדור',    emoji: '⚽', cat: 'objects'  },
      { word: 'Hat',    heWord: 'כובע',    emoji: '🎩', cat: 'objects'  },
      { word: 'Cup',    heWord: 'כוס',     emoji: '☕', cat: 'objects'  },
      { word: 'Pig',    heWord: 'חזיר',    emoji: '🐷', cat: 'animals'  },
      { word: 'Sun',    heWord: 'שמש',     heSpeech: 'שֶׁמֶשׁ',    emoji: '☀️', cat: 'nature'   },
      { word: 'Fish',   heWord: 'דג',      emoji: '🐟', cat: 'animals'  },
      { word: 'Bird',   heWord: 'ציפור',   heSpeech: 'צִיפּוֹר',  emoji: '🐦', cat: 'animals'  },
      { word: 'Tree',   heWord: 'עץ',      emoji: '🌳', cat: 'nature'   },
      { word: 'Book',   heWord: 'ספר',     emoji: '📚', cat: 'objects'  },
    ],
  },
  {
    id: 2,
    cardCount: 3,
    winsToWin: 6,
    wordPool: [
      { word: 'Cat',    heWord: 'חתול',    emoji: '🐱', cat: 'animals'  },
      { word: 'Bear',   heWord: 'דוב',     emoji: '🐻', cat: 'animals'  },
      { word: 'Bee',    heWord: 'דבורה',   heSpeech: 'דְּבוֹרָה', emoji: '🐝', cat: 'animals'  },
      { word: 'Cow',    heWord: 'פרה',     heSpeech: 'פָּרָה',    emoji: '🐮', cat: 'animals'  },
      { word: 'Duck',   heWord: 'ברווז',   heSpeech: 'בַּרְוָז',  emoji: '🦆', cat: 'animals'  },
      { word: 'Frog',   heWord: 'צפרדע',  emoji: '🐸', cat: 'animals'  },
      { word: 'Rabbit', heWord: 'ארנב',    emoji: '🐰', cat: 'animals'  },
      { word: 'Hen',    heWord: 'תרנגולת', emoji: '🐔', cat: 'animals'  },
      { word: 'Corn',   heWord: 'תירס',    emoji: '🌽', cat: 'food'     },
      { word: 'Bed',    heWord: 'מיטה',    emoji: '🛏️', cat: 'objects'  },
    ],
  },
  {
    id: 3,
    cardCount: 4,
    winsToWin: 7,
    wordPool: [
      { word: 'Cake',   heWord: 'עוגה',    emoji: '🎂', cat: 'food'     },
      { word: 'Moon',   heWord: 'ירח',     heSpeech: 'יָרֵחַ',    emoji: '🌙', cat: 'nature'   },
      { word: 'Star',   heWord: 'כוכב',    heSpeech: 'כּוֹכָב',   emoji: '⭐', cat: 'nature'   },
      { word: 'Egg',    heWord: 'ביצה',    heSpeech: 'בֵּיצָה',   emoji: '🥚', cat: 'food'     },
      { word: 'Milk',   heWord: 'חלב',     heSpeech: 'חָלָב',     emoji: '🥛', cat: 'food'     },
      { word: 'Key',    heWord: 'מפתח',    heSpeech: 'מַפְתֵּחַ', emoji: '🔑', cat: 'objects'  },
      { word: 'Bus',    heWord: 'אוטובוס', emoji: '🚌', cat: 'vehicles' },
      { word: 'Ship',   heWord: 'ספינה',   emoji: '🚢', cat: 'vehicles' },
    ],
  },
  {
    id: 4,
    cardCount: 4,
    winsToWin: 8,
    wordPool: [
      // All 30 words combined
      { word: 'Apple',  heWord: 'תפוח',    emoji: '🍎', cat: 'food'     },
      { word: 'Dog',    heWord: 'כלב',     emoji: '🐶', cat: 'animals'  },
      { word: 'Car',    heWord: 'מכונית',  emoji: '🚗', cat: 'vehicles' },
      { word: 'Ball',   heWord: 'כדור',    emoji: '⚽', cat: 'objects'  },
      { word: 'Hat',    heWord: 'כובע',    emoji: '🎩', cat: 'objects'  },
      { word: 'Cup',    heWord: 'כוס',     emoji: '☕', cat: 'objects'  },
      { word: 'Pig',    heWord: 'חזיר',    emoji: '🐷', cat: 'animals'  },
      { word: 'Sun',    heWord: 'שמש',     heSpeech: 'שֶׁמֶשׁ',    emoji: '☀️', cat: 'nature'   },
      { word: 'Fish',   heWord: 'דג',      emoji: '🐟', cat: 'animals'  },
      { word: 'Bird',   heWord: 'ציפור',   heSpeech: 'צִיפּוֹר',  emoji: '🐦', cat: 'animals'  },
      { word: 'Tree',   heWord: 'עץ',      emoji: '🌳', cat: 'nature'   },
      { word: 'Book',   heWord: 'ספר',     emoji: '📚', cat: 'objects'  },
      { word: 'Cat',    heWord: 'חתול',    emoji: '🐱', cat: 'animals'  },
      { word: 'Bear',   heWord: 'דוב',     emoji: '🐻', cat: 'animals'  },
      { word: 'Bee',    heWord: 'דבורה',   heSpeech: 'דְּבוֹרָה', emoji: '🐝', cat: 'animals'  },
      { word: 'Cow',    heWord: 'פרה',     heSpeech: 'פָּרָה',    emoji: '🐮', cat: 'animals'  },
      { word: 'Duck',   heWord: 'ברווז',   heSpeech: 'בַּרְוָז',  emoji: '🦆', cat: 'animals'  },
      { word: 'Frog',   heWord: 'צפרדע',  emoji: '🐸', cat: 'animals'  },
      { word: 'Rabbit', heWord: 'ארנב',    emoji: '🐰', cat: 'animals'  },
      { word: 'Hen',    heWord: 'תרנגולת', emoji: '🐔', cat: 'animals'  },
      { word: 'Corn',   heWord: 'תירס',    emoji: '🌽', cat: 'food'     },
      { word: 'Bed',    heWord: 'מיטה',    emoji: '🛏️', cat: 'objects'  },
      { word: 'Cake',   heWord: 'עוגה',    emoji: '🎂', cat: 'food'     },
      { word: 'Moon',   heWord: 'ירח',     heSpeech: 'יָרֵחַ',    emoji: '🌙', cat: 'nature'   },
      { word: 'Star',   heWord: 'כוכב',    heSpeech: 'כּוֹכָב',   emoji: '⭐', cat: 'nature'   },
      { word: 'Egg',    heWord: 'ביצה',    heSpeech: 'בֵּיצָה',   emoji: '🥚', cat: 'food'     },
      { word: 'Milk',   heWord: 'חלב',     heSpeech: 'חָלָב',     emoji: '🥛', cat: 'food'     },
      { word: 'Key',    heWord: 'מפתח',    heSpeech: 'מַפְתֵּחַ', emoji: '🔑', cat: 'objects'  },
      { word: 'Bus',    heWord: 'אוטובוס', emoji: '🚌', cat: 'vehicles' },
      { word: 'Ship',   heWord: 'ספינה',   emoji: '🚢', cat: 'vehicles' },
    ],
  },
];
