// Level 1: 2 cards — simple, familiar single-syllable words
// Level 2: 3 cards — common 2-syllable words, broader vocabulary
// Level 3: 4 cards — multi-syllable, exotic animals & objects (genuinely hard)
// Level 4: 4 cards — rare/abstract words + full pool from all levels combined

export const LEVELS = [
  {
    id: 1,
    cardCount: 2,
    winsToWin: 5,
    wordPool: [
      { word: 'Apple',  heWord: 'תפוח',    emoji: '🍎', cat: 'food'     },
      { word: 'Dog',    heWord: 'כלב',     emoji: '🐶', cat: 'animals'  },
      { word: 'Car',    heWord: 'מכונית',  emoji: '🚗', cat: 'vehicles' },
      { word: 'Ball',   heWord: 'כדור',    emoji: '⚽', cat: 'objects'  },
      { word: 'Hat',    heWord: 'כובע',    emoji: '🎩', cat: 'objects'  },
      { word: 'Cup',    heWord: 'כוס',     emoji: '☕', cat: 'objects'  },
      { word: 'Pig',    heWord: 'חזיר',    emoji: '🐷', cat: 'animals'  },
      { word: 'Sun',    heWord: 'שמש',     heSpeech: 'שֶׁמֶשׁ',    emoji: '☀️', cat: 'nature'   },
      { word: 'Fish',   heWord: 'דג',      emoji: '🐟', cat: 'animals'  },
      { word: 'Bird',   heWord: 'ציפור',   heSpeech: 'צִיפּוֹר',  emoji: '🐦', cat: 'animals'  },
      { word: 'Tree',   heWord: 'עץ',      emoji: '🌳', cat: 'nature'   },
      { word: 'Book',   heWord: 'ספר',     emoji: '📚', cat: 'objects'  },
    ],
  },
  {
    id: 2,
    cardCount: 3,
    winsToWin: 6,
    wordPool: [
      { word: 'Cat',    heWord: 'חתול',    emoji: '🐱', cat: 'animals'  },
      { word: 'Bear',   heWord: 'דוב',     emoji: '🐻', cat: 'animals'  },
      { word: 'Bee',    heWord: 'דבורה',   heSpeech: 'דְּבוֹרָה', emoji: '🐝', cat: 'animals'  },
      { word: 'Cow',    heWord: 'פרה',     heSpeech: 'פָּרָה',    emoji: '🐮', cat: 'animals'  },
      { word: 'Duck',   heWord: 'ברווז',   heSpeech: 'בַּרְוָז',  emoji: '🦆', cat: 'animals'  },
      { word: 'Frog',   heWord: 'צפרדע',  emoji: '🐸', cat: 'animals'  },
      { word: 'Rabbit', heWord: 'ארנב',    emoji: '🐰', cat: 'animals'  },
      { word: 'Hen',    heWord: 'תרנגולת', emoji: '🐔', cat: 'animals'  },
      { word: 'Cake',   heWord: 'עוגה',    emoji: '🎂', cat: 'food'     },
      { word: 'Egg',    heWord: 'ביצה',    heSpeech: 'בֵּיצָה',   emoji: '🥚', cat: 'food'     },
      { word: 'Milk',   heWord: 'חלב',     heSpeech: 'חָלָב',     emoji: '🥛', cat: 'food'     },
      { word: 'Moon',   heWord: 'ירח',     heSpeech: 'יָרֵחַ',    emoji: '🌙', cat: 'nature'   },
      { word: 'Star',   heWord: 'כוכב',    heSpeech: 'כּוֹכָב',   emoji: '⭐', cat: 'nature'   },
      { word: 'Bus',    heWord: 'אוטובוס', emoji: '🚌', cat: 'vehicles' },
      { word: 'Ship',   heWord: 'ספינה',   emoji: '🚢', cat: 'vehicles' },
    ],
  },
  {
    id: 3,
    cardCount: 4,
    winsToWin: 7,
    wordPool: [
      { word: 'Elephant',   heWord: 'פיל',       emoji: '🐘', cat: 'animals'  },
      { word: 'Dinosaur',   heWord: 'דינוזאור',  emoji: '🦕', cat: 'animals'  },
      { word: 'Kangaroo',   heWord: 'קנגורו',    emoji: '🦘', cat: 'animals'  },
      { word: 'Penguin',    heWord: 'פינגווין',  emoji: '🐧', cat: 'animals'  },
      { word: 'Crocodile',  heWord: 'תנין',      emoji: '🐊', cat: 'animals'  },
      { word: 'Octopus',    heWord: 'תמנון',     emoji: '🐙', cat: 'animals'  },
      { word: 'Flamingo',   heWord: 'פלמינגו',   emoji: '🦩', cat: 'animals'  },
      { word: 'Scorpion',   heWord: 'עקרב',      heSpeech: 'עַקְרָב', emoji: '🦂', cat: 'animals'  },
      { word: 'Jellyfish',  heWord: 'מדוזה',     emoji: '🪼', cat: 'animals'  },
      { word: 'Peacock',    heWord: 'טווס',      emoji: '🦚', cat: 'animals'  },
      { word: 'Dragon',     heWord: 'דרקון',     emoji: '🐉', cat: 'animals'  },
      { word: 'Unicorn',    heWord: 'חד קרן',    emoji: '🦄', cat: 'animals'  },
      { word: 'Helicopter', heWord: 'מסוק',      emoji: '🚁', cat: 'vehicles' },
      { word: 'Rocket',     heWord: 'רקטה',      heSpeech: 'רָקֶטָה', emoji: '🚀', cat: 'vehicles' },
      { word: 'Volcano',    heWord: 'הר געש',    emoji: '🌋', cat: 'nature'   },
      { word: 'Strawberry', heWord: 'תות',       emoji: '🍓', cat: 'food'     },
      { word: 'Pineapple',  heWord: 'אננס',      emoji: '🍍', cat: 'food'     },
      { word: 'Umbrella',   heWord: 'מטריה',     emoji: '☂️', cat: 'objects'  },
    ],
  },
  {
    id: 4,
    cardCount: 4,
    winsToWin: 8,
    wordPool: [
      // Level 1 words
      { word: 'Apple',      heWord: 'תפוח',      emoji: '🍎', cat: 'food'     },
      { word: 'Dog',        heWord: 'כלב',       emoji: '🐶', cat: 'animals'  },
      { word: 'Car',        heWord: 'מכונית',    emoji: '🚗', cat: 'vehicles' },
      { word: 'Ball',       heWord: 'כדור',      emoji: '⚽', cat: 'objects'  },
      { word: 'Hat',        heWord: 'כובע',      emoji: '🎩', cat: 'objects'  },
      { word: 'Cup',        heWord: 'כוס',       emoji: '☕', cat: 'objects'  },
      { word: 'Pig',        heWord: 'חזיר',      emoji: '🐷', cat: 'animals'  },
      { word: 'Sun',        heWord: 'שמש',       heSpeech: 'שֶׁמֶשׁ',    emoji: '☀️', cat: 'nature'   },
      { word: 'Fish',       heWord: 'דג',        emoji: '🐟', cat: 'animals'  },
      { word: 'Bird',       heWord: 'ציפור',     heSpeech: 'צִיפּוֹר',  emoji: '🐦', cat: 'animals'  },
      { word: 'Tree',       heWord: 'עץ',        emoji: '🌳', cat: 'nature'   },
      { word: 'Book',       heWord: 'ספר',       emoji: '📚', cat: 'objects'  },
      // Level 2 words
      { word: 'Cat',        heWord: 'חתול',      emoji: '🐱', cat: 'animals'  },
      { word: 'Bear',       heWord: 'דוב',       emoji: '🐻', cat: 'animals'  },
      { word: 'Bee',        heWord: 'דבורה',     heSpeech: 'דְּבוֹרָה', emoji: '🐝', cat: 'animals'  },
      { word: 'Cow',        heWord: 'פרה',       heSpeech: 'פָּרָה',    emoji: '🐮', cat: 'animals'  },
      { word: 'Duck',       heWord: 'ברווז',     heSpeech: 'בַּרְוָז',  emoji: '🦆', cat: 'animals'  },
      { word: 'Frog',       heWord: 'צפרדע',    emoji: '🐸', cat: 'animals'  },
      { word: 'Rabbit',     heWord: 'ארנב',      emoji: '🐰', cat: 'animals'  },
      { word: 'Cake',       heWord: 'עוגה',      emoji: '🎂', cat: 'food'     },
      { word: 'Moon',       heWord: 'ירח',       heSpeech: 'יָרֵחַ',    emoji: '🌙', cat: 'nature'   },
      { word: 'Star',       heWord: 'כוכב',      heSpeech: 'כּוֹכָב',   emoji: '⭐', cat: 'nature'   },
      { word: 'Bus',        heWord: 'אוטובוס',   emoji: '🚌', cat: 'vehicles' },
      // Level 3 words
      { word: 'Elephant',   heWord: 'פיל',       emoji: '🐘', cat: 'animals'  },
      { word: 'Dinosaur',   heWord: 'דינוזאור',  emoji: '🦕', cat: 'animals'  },
      { word: 'Kangaroo',   heWord: 'קנגורו',    emoji: '🦘', cat: 'animals'  },
      { word: 'Penguin',    heWord: 'פינגווין',  emoji: '🐧', cat: 'animals'  },
      { word: 'Crocodile',  heWord: 'תנין',      emoji: '🐊', cat: 'animals'  },
      { word: 'Octopus',    heWord: 'תמנון',     emoji: '🐙', cat: 'animals'  },
      { word: 'Flamingo',   heWord: 'פלמינגו',   emoji: '🦩', cat: 'animals'  },
      { word: 'Scorpion',   heWord: 'עקרב',      heSpeech: 'עַקְרָב', emoji: '🦂', cat: 'animals'  },
      { word: 'Jellyfish',  heWord: 'מדוזה',     emoji: '🪼', cat: 'animals'  },
      { word: 'Peacock',    heWord: 'טווס',      emoji: '🦚', cat: 'animals'  },
      { word: 'Dragon',     heWord: 'דרקון',     emoji: '🐉', cat: 'animals'  },
      { word: 'Unicorn',    heWord: 'חד קרן',    emoji: '🦄', cat: 'animals'  },
      { word: 'Helicopter', heWord: 'מסוק',      emoji: '🚁', cat: 'vehicles' },
      { word: 'Rocket',     heWord: 'רקטה',      heSpeech: 'רָקֶטָה', emoji: '🚀', cat: 'vehicles' },
      { word: 'Volcano',    heWord: 'הר געש',    emoji: '🌋', cat: 'nature'   },
      { word: 'Strawberry', heWord: 'תות',       emoji: '🍓', cat: 'food'     },
      { word: 'Pineapple',  heWord: 'אננס',      emoji: '🍍', cat: 'food'     },
      { word: 'Umbrella',   heWord: 'מטריה',     emoji: '☂️', cat: 'objects'  },
      // Expert-only words
      { word: 'Telescope',  heWord: 'טלסקופ',    emoji: '🔭', cat: 'objects'  },
      { word: 'Compass',    heWord: 'מצפן',      emoji: '🧭', cat: 'objects'  },
      { word: 'Magnet',     heWord: 'מגנט',      emoji: '🧲', cat: 'objects'  },
      { word: 'Hourglass',  heWord: 'שעון חול',  emoji: '⏳', cat: 'objects'  },
      { word: 'Trophy',     heWord: 'גביע',      emoji: '🏆', cat: 'objects'  },
      { word: 'Tornado',    heWord: 'טורנדו',    emoji: '🌪️', cat: 'nature'   },
      { word: 'Hurricane',  heWord: 'הוריקן',    emoji: '🌀', cat: 'nature'   },
      { word: 'Lightning',  heWord: 'ברק',       emoji: '⚡', cat: 'nature'   },
      { word: 'Gorilla',    heWord: 'גורילה',    emoji: '🦍', cat: 'animals'  },
      { word: 'Chameleon',  heWord: 'זיקית',     emoji: '🦎', cat: 'animals'  },
      { word: 'Hedgehog',   heWord: 'קיפוד',     emoji: '🦔', cat: 'animals'  },
      { word: 'Walrus',     heWord: 'ולרוס',     emoji: '🦭', cat: 'animals'  },
      { word: 'Mammoth',    heWord: 'ממות',      emoji: '🦣', cat: 'animals'  },
      { word: 'Mushroom',   heWord: 'פטרייה',    emoji: '🍄', cat: 'food'     },
    ],
  },
];
