export const SCENARIOS = [
  {
    id: 3,
    video: 'videos/scenario-3.mp4',
    scene: '⚽👫🙋',
    sceneEmojis: ['⚽', '👫', '🙋'],
    sceneAnims: ['spin', 'bounce', 'wave'],
    situation: 'אני רוצה להצטרף למשחק של חברים',
    situationEn: "I want to join my friends' game",
    prompt: 'מה הכי נכון להגיד?',
    promptEn: 'What is the best thing to say?',
    tts: 'אתה רוצה להצטרף למשחק של חברים. מה הכי נכון להגיד?',
    ttsFallback: "You want to join your friends' game. What is the best thing to say?",
    options: [
      { emoji: '😊', text: 'אני שואל: "אפשר גם אני?"', textEn: "I ask: 'Can I join too?'", quality: 'best' },
      { emoji: '😠', text: 'אני נכנס למשחק בלי לשאול', textEn: 'I join the game without asking', quality: 'notGood' },
    ],
    lesson: 'קודם שואלים, ואז מצטרפים למשחק.',
    lessonFallback: 'First ask, then join the game.',
  },
  {
    id: 1,
    video: 'videos/scenario-1.mp4',
    scene: '🧒😤🪀',
    sceneEmojis: ['🧒', '😤', '🪀'],
    sceneAnims: ['float', 'shake', 'bounce'],
    situation: 'חבר לקח את הצעצוע שלך',
    situationEn: 'A friend took your toy',
    prompt: 'מה הכי נכון להגיד?',
    promptEn: 'What is the best thing to say?',
    tts: 'חבר לקח את הצעצוע שלך. מה הכי נכון להגיד?',
    ttsFallback: 'A friend took your toy. What is the best thing to say?',
    options: [
      { emoji: '🗣️', text: 'אני אומר: "זה שלי, תחזיר לי בבקשה"', textEn: "I say: 'That is mine, please give it back'", quality: 'best' },
      { emoji: '👊', text: 'אני דוחף אותו', textEn: 'I push them', quality: 'notGood' },
    ],
    lesson: 'כשמשהו מפריע לי, אני קודם משתמש במילים.',
    lessonFallback: 'When something bothers me, I use words first.',
  },
  {
    id: 4,
    video: 'videos/scenario-4.mp4',
    scene: '🧒😢💙',
    sceneEmojis: ['🧒', '😢', '💙'],
    sceneAnims: ['float', 'cry', 'pulse'],
    situation: 'חבר שלי בוכה ועצוב',
    situationEn: 'My friend is crying and sad',
    prompt: 'מה כדאי לעשות?',
    promptEn: 'What should I do?',
    tts: 'חבר שלך בוכה ועצוב. מה כדאי לעשות?',
    ttsFallback: 'Your friend is crying and sad. What should you do?',
    options: [
      { emoji: '🤗', text: 'אני ניגש ואומר: "אני כאן בשבילך"', textEn: "I go over and say: 'I am here for you'", quality: 'best' },
      { emoji: '🏃', text: 'אני ממשיך לשחק ולא מתייחס', textEn: 'I keep playing and ignore them', quality: 'notGood' },
    ],
    lesson: 'כשחבר עצוב, עוצרים רגע ומראים אכפתיות.',
    lessonFallback: 'When a friend is sad, pause and show care.',
  },
  {
    id: 5,
    video: 'videos/scenario-5.mp4',
    scene: '🧒😳💔',
    sceneEmojis: ['🧒', '😳', '💔'],
    sceneAnims: ['shake', 'pulse', 'pulse'],
    situation: 'עשיתי טעות ושברתי משהו',
    situationEn: 'I made a mistake and broke something',
    prompt: 'מה הכי נכון לעשות?',
    promptEn: 'What is the best thing to do?',
    tts: 'עשית טעות ושברת משהו. מה הכי נכון לעשות?',
    ttsFallback: 'You made a mistake and broke something. What is the best thing to do?',
    options: [
      { emoji: '🙏', text: 'אני אומר: "סליחה, זה קרה לי בטעות"', textEn: "I say: 'Sorry, it happened by mistake'", quality: 'best' },
      { emoji: '🏃', text: 'אני בורח ולא אומר כלום', textEn: 'I run away and say nothing', quality: 'notGood' },
    ],
    lesson: 'גם כשקשה, אומרים את האמת ומבקשים סליחה.',
    lessonFallback: 'Even when it is hard, tell the truth and say sorry.',
  },
  {
    id: 2,
    video: 'videos/scenario-2.mp4',
    scene: '🧒😢👫',
    sceneEmojis: ['🧒', '😢', '👫'],
    sceneAnims: ['float', 'cry', 'bounce'],
    situation: 'אף אחד לא רוצה לשחק איתי',
    situationEn: 'Nobody wants to play with me',
    prompt: 'מה אני יכול להגיד?',
    promptEn: 'What can I say?',
    tts: 'אף אחד לא רוצה לשחק איתך. מה אתה יכול להגיד?',
    ttsFallback: 'Nobody wants to play with you. What can you say?',
    options: [
      { emoji: '🤗', text: 'אני שואל: "אפשר לשחק איתכם?"', textEn: "I ask: 'Can I play with you?'", quality: 'best' },
      { emoji: '😭', text: 'אני בוכה ובורח', textEn: 'I cry and run away', quality: 'notGood' },
    ],
    lesson: 'כשאני רוצה להצטרף, אני מנסה לבקש בצורה ברורה ונעימה.',
    lessonFallback: 'When I want to join, I ask clearly and kindly.',
  },
  {
    id: 6,
    video: 'videos/scenario-6.mp4',
    scene: '🧒💢🧒',
    sceneEmojis: ['🧒', '💢', '🧒'],
    sceneAnims: ['shake', 'pulse', 'float'],
    situation: 'חבר דוחף אותי',
    situationEn: 'A friend is pushing me',
    prompt: 'מה כדאי לעשות עכשיו?',
    promptEn: 'What should I do now?',
    tts: 'חבר דוחף אותך. מה כדאי לעשות עכשיו?',
    ttsFallback: 'A friend is pushing you. What should you do now?',
    options: [
      { emoji: '🙋', text: 'אני אומר: "אל תדחוף" ומספר למורה', textEn: "I say: 'Do not push' and tell the teacher", quality: 'best' },
      { emoji: '👊', text: 'אני דוחף בחזרה', textEn: 'I push back', quality: 'notGood' },
    ],
    lesson: 'כשלא בטוח לי, אני שומר על עצמי ופונה למבוגר.',
    lessonFallback: 'When it does not feel safe, I protect myself and tell an adult.',
  },
  {
    id: 8,
    video: 'videos/scenario-8.mp4',
    scene: '🧒😤😆',
    sceneEmojis: ['🧒', '😤', '😆'],
    sceneAnims: ['float', 'shake', 'bounce'],
    situation: 'מישהו צוחק עליי',
    situationEn: 'Someone is laughing at me',
    prompt: 'מה כדאי לעשות עכשיו?',
    promptEn: 'What should I do now?',
    tts: 'מישהו צוחק עליך. מה כדאי לעשות עכשיו?',
    ttsFallback: 'Someone is laughing at you. What should you do now?',
    options: [
      { emoji: '🚶', text: 'אני מתרחק ומספר למבוגר', textEn: 'I walk away and tell an adult', quality: 'best' },
      { emoji: '😡', text: 'אני צועק עליו בחזרה', textEn: 'I yell back at them', quality: 'notGood' },
    ],
    lesson: 'לא חייבים להחזיר. אפשר להתרחק ולבקש עזרה.',
    lessonFallback: 'You do not have to fight back. You can walk away and ask for help.',
  },
  {
    id: 7,
    video: 'videos/scenario-7.mp4',
    scene: '🧒😠🤝',
    sceneEmojis: ['🧒', '😠', '🤝'],
    sceneAnims: ['float', 'shake', 'pulse'],
    situation: 'מישהו אומר: "אם לא תיתן לי, אני לא חבר שלך"',
    situationEn: '"If you do not give me that, I am not your friend"',
    prompt: 'מה הכי נכון להגיד?',
    promptEn: 'What is the best thing to say?',
    tts: 'מישהו אומר: אם לא תיתן לי, אני לא חבר שלך. מה הכי נכון להגיד?',
    ttsFallback: 'Someone says: If you do not give me that, I am not your friend. What is the best thing to say?',
    options: [
      { emoji: '💪', text: 'אני אומר: "חבר אמיתי לא מאיים"', textEn: "I say: 'A real friend does not threaten'", quality: 'best' },
      { emoji: '😰', text: 'אני נותן לו כי אני פוחד', textEn: 'I give it because I am scared', quality: 'notGood' },
    ],
    lesson: 'מותר לי לשמור על עצמי וגם לומר לא.',
    lessonFallback: 'It is okay to protect myself and say no.',
  },
  {
    id: 10,
    video: 'videos/scenario-10.mp4',
    scene: '🧒😟🚫',
    sceneEmojis: ['🧒', '😟', '🚫'],
    sceneAnims: ['float', 'cry', 'pulse'],
    situation: 'חבר אומר לי לעשות משהו שנראה לא בסדר',
    situationEn: 'A friend wants me to do something that feels wrong',
    prompt: 'מה הכי נכון לעשות?',
    promptEn: 'What is the best thing to do?',
    tts: 'חבר מבקש ממך לעשות משהו שנראה לא בסדר. מה הכי נכון לעשות?',
    ttsFallback: 'A friend asks you to do something that feels wrong. What is the best thing to do?',
    options: [
      { emoji: '🙅', text: 'אני אומר: "לא" ומספר למבוגר', textEn: "I say: 'No' and tell an adult", quality: 'best' },
      { emoji: '😰', text: 'אני עושה את זה כי הוא חבר שלי', textEn: "I do it because they are my friend", quality: 'notGood' },
    ],
    lesson: 'אם משהו מרגיש לא בסדר, מותר לעצור ולספר.',
    lessonFallback: 'If something feels wrong, it is okay to stop and tell someone.',
  },
  {
    id: 9,
    video: 'videos/scenario-9.mp4',
    scene: '🤫😨🙅',
    sceneEmojis: ['🤫', '😨', '🙅'],
    sceneAnims: ['pulse', 'shake', 'wave'],
    situation: 'מישהו מבקש שאשמור סוד שמפחיד אותי',
    situationEn: 'Someone asks me to keep a secret that scares me',
    prompt: 'למי אני צריך לספר?',
    promptEn: 'Who should I tell?',
    tts: 'מישהו מבקש ממך לשמור סוד שמפחיד אותך. למי אתה צריך לספר?',
    ttsFallback: 'Someone asks you to keep a secret that scares you. Who should you tell?',
    options: [
      { emoji: '👩‍🏫', text: 'אני מספר לאמא, אבא או מורה', textEn: 'I tell mom, dad, or a teacher', quality: 'best' },
      { emoji: '🤐', text: 'אני שומר את זה לבד', textEn: 'I keep it to myself', quality: 'notGood' },
    ],
    lesson: 'סוד מפחיד לא שומרים לבד. תמיד מספרים למבוגר שסומכים עליו.',
    lessonFallback: 'Do not keep a scary secret alone. Always tell a trusted adult.',
  },
];
